name: Run crank

on:
  workflow_dispatch:

jobs:
  run-crank:
    name: Fetch data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: npm

      - name: Install Dependencies
        id: yarn-ci
        run: yarn install

      - name: Run bot
        id: run-bot
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
        run: yarn start
